### PR TITLE
Silent install

### PR DESCRIPTION
**Pull request by AeliusSaionji**
An argument to the script which
a) don't require the user to press enter
b) doesn't open the control panel

I'm trying to build a Chocolatey package, complete silence and automation is required. I'm not the best at batch script, so if this PR isn't up to your standards, please implement this feature in your own way.

### CODE REVIEW

**Comment by AeliusSaionji** [comment]
I decided it would be a good idea to test this, and it breaks the whole script. Batch! _shakes fist_

**Comment by AeliusSaionji** [comment]
No... something else was wrong with the way I ran it, I guess? This does work.

**Comment by rossy** [comment]
Thanks, this is a good idea. I took the opportunity to implement it in my own way because the script also calls `pause` on failure and I think that should work without user interaction too. I also changed the command line switch to `\u` (for an **u**nattended install.) I wasn't comfortable calling it "silent" because the scripts still print stuff to the console when it is set. Hopefully this is okay.

**Comment by AeliusSaionji** [comment]
Perfect, thanks. I'll test it out soon

**Pull request closed without merging**
